### PR TITLE
Add new verbose logging level filter

### PR DESCRIPTION
**Pull request by cevich**
This actually implements --verbose, by defining two levels
of INFO messages:

    logging.info("This is always displayed")
    logging.info(">Shown only if --verbose")

That is: if message begins with '>', it is filtered out
by default but shown if --verbose (or --debug). The
leading '>' is stripped.

I considered reversing the sense of the test: filtering
out INFO messages by default, and showing only those
starting with '!' or '*' or something. I think that
would be counterintuitive, so I went with show-unless->
even though that makes this diff larger.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@edsantiago okay, this is working now and passing all the tests I could throw at it.  PTAL in case I goofed something, though it should be really really close to the work you did.

**Comment by edsantiago** [comment]
LGTM but I can't make sense of the CI failure

**Comment by cevich** [comment]
Ahh, it's just missing an indentation space, got it.

**Comment by cevich** [comment]
okay, that should do it.  I also split out the few small changes I made into separate commits.

**Pull request closed without merging**
